---
title: "ALUMNI"
---
***

<h2>Graduates</h2>

*	 Arisnel Soto, PhD
*  David Quispe-Parra, M.S.
*	 Jorge Viera-Vera
*	 Jose Alexis Rodriguez, M.S.
*	 Miosotis Alicea Delgado, M.S.
*	 Samir Bello, PhD

<h2>Undergraduates</h2>

*  Adrian Medina
*	 Adrianna M. Rivera-León
*	 Alejandro Cedeño
*	 Alexandra Amador
*  Amanda Morales
*  Andrea Rodriguez
*	 Angel Sirfa
*	 Angela Colon
*	 Angelica Romero
*	 Ashley Soriano
*	 Carlos Martinez
*	 Carlos Rodriguez
*	 Charlotte De Jesús
*  Christian Andino
*	 Cristina Gerena
*	 Daniel Fontanez
*	 Daniela Díaz-Rubayo
*  Diego Calo
*  Eduardo Quesada
*	 Edward Lugo
*  Emil Gonzalez
*	 Eveliz Peguero
*	 Fabiola Sotomayor
*	 Gabriela Rodríguez Morales
*	 Javier Jusino
*	 Josean Reyes Rivera
*	 Joseph Salem
*  Kamyla Reyes
*  Karina Peña
*  Kevin Santiago
*  Kianna Franco
*	 Kidianys Sanchez
*	 Luis Medina
*  Marianny Alvarado
*	 Mayra Betancourt
*  Miozzottys Perez
*  Naomi Cruz
*	 Natalia Rosario
*	 Natalia Torres
*  Omar Morales
*  Omar Perez
*	 Pablo Rosado
*	 Paola Figueroa-Delgado
*	 Raul García
*	 Rey Rosa
*	 Rolando Vargas
*	 Ruben García
*	 Samuel Álvarez
*	 Sarah Colón
*	 Sebastian Cruz
*	 Sergio Maldonado
*	 Sonya Jadaas Malavez
*	 Stephanie Colón
*	 Tathana Rivera
*  Thaybet Malavé
*	 Valentina Grillo
*	 Vanessa Torres
*	 Wilyaret Rodriguez
*  Yariel Figueroa

***